POST http://localhost:3000/api/calcula-comissao HTTP/1.1
content-type: application/json

{
  "pedidos": [
    { "vendedor": 1, "data": "2022-03-01", "valor": 500.34 },
    { "vendedor": 1, "data": "2022-03-01", "valor": 1000.22 },
    { "vendedor": 1, "data": "2022-03-01", "valor": 100.35 },
    { "vendedor": 1, "data": "2022-03-01", "valor": 22.34 },
    { "vendedor": 1, "data": "2022-04-01", "valor": 5000.34 },
    { "vendedor": 2, "data": "2022-03-01", "valor": 2000.34 },
    { "vendedor": 2, "data": "2022-04-01", "valor": 3000.34 }
  ]
}